### ISSUE TITLE
ModernFix

### ISSUE THREAD

**Issue by Aquoo** [intergrav/adrenaline#24]
ModernFix is a performance mod which reduces startup time and improves memory usage.

https://modrinth.com/mod/modernfix

**Comment by MenacingPerson** [comment]
Please reopen this. ModernFix's dynamic resource loading option (disabled by default) and faster item rendering (also disabled by default) are quite good.

**Comment by MenacingPerson** [comment]
For a config file, look [here](https://github.com/MenacingPerson/Multiplicative/blob/main/conf/1.19.4/config/yosbr/modernfix-mixins.properties)

**Comment by intergrav** [comment]
Ever since HyperSoop added ModernFix to Simply Optimized I've been considering adding it to Adrenaline, I was waiting for a few critical bugs to be fixed but I assume those have probably been fixed by now. Just haven't looked into the mod in a while :p 
It definitely seems stable enough to be included at this point.

**Comment by intergrav** [comment]
Included in Adrenaline 1.15.0 and Additive 1.18.0
