### ISSUE TITLE
Replace Sodium with Embeddium

### ISSUE THREAD

**Issue by Coccocoahelper** [intergrav/Adrenaline#40]
**Is your request related to a problem? Please describe if so.**

**Describe the mod you'd like to add, remove, or change**
I'd like for Sodium to be replaced with Embeddium, and for Indium to be removed, since it won't be necessary (Embeddium does that anyway). The reason for this is freedom; Sodium no longer protects software freedom, and Embeddium is quite good right now. 

**List alternative mods or solutions you've considered**

**Additional context**

**Comment by Coccocoahelper** [comment]
> You are playing a proprietary game (with DRM) on what is likely a proprietary launcher and proprietary web platform from which to download those mods from. Sodium's licensing does not impact the user experience in any conceivable way, nor does it prevent anyone from including it in modpacks.

(I am aware that you are the owner of CaffeineMC, and therefore of Sodium)

I'm on Prism Launcher, I use Modrinth, and I am a developer (albeit a mid one) too. I will probably edit mods at some point, and maybe even redistribute them, and since most mods are on GPLv3, it will be difficult to add things I deem necessary back and forth.

**Comment by SrRapero720** [comment]
> I will probably edit mods at some point, and maybe even redistribute them, and since most mods are on GPLv3, it will be difficult to add things I deem necessary back and forth.

This is not your modpack, so why are you getting concerned about? At least you have even the need of modify sodium nor embeddium in any moment? people still can download and include sodium on their modpacks.

Having a restrictive license or even begin ARR doesn't mean you can't edit or redistribute projects from someone else (if you ask to the author). You can always go to the project's github or the author discord and ask nicely about your intensions about editing the mod, what is your project and how will be done the changes, probably you will receive the permission or an special license for it (of course with some conditons), or even better; accept your changes and got merged directly on the mod.

The reason of this decision (paraphrasing jellys words) is for some people was forking jellysquid mods just to say "fakiu jellysquid" and your behavior is basically reinforcing the decision.

Concerns a lot about how many young devs yells for "software freedom" when first you didn't even need to modify sodium or affects you, you're using a lot of non-free closed source piece of software. Not everything should be open source or "free software", Otherwise nobody will do software if you won't get rewarded about.

embeddium is not an replacement of sodium, is an alternative, like Github an Gitlab. You can choose one of them if you feel the game runs better with it, (or if you're a license paranoid). You can always download/update the modpack, remove sodium and install embeddium, or even ask for an alternative version with embeddium. in both cases both mods get supported. Not just yell "yeah sodium bad, embeddium good". That just hurts the image of both authors.
